Algoritmo "oeracaoMatematica"

Var
  a, b, c, x : inteiro

Inicio
      escreval("Vamos resolver a seguinte expressão: x = (a+(b x c))")
      escreval("Digite  o valor de a: ")
      leia (a)
      escreval("Digite  o valor de b: ")
      leia (b)
      escreval("Digite  o valor de c: ")
      leia (c)
      x <- (a + (b*c))
      escreva ("O resultado da expressão é: ",x,".")
      



Fimalgoritmo